services:


  gotenberg:
    image: gotenberg/gotenberg:latest

    networks:
      - swarm_public

    environment:
      - GOTENBERG_API_DISABLE_HEALTH_CHECK_LOG=${GOTENBERG_API_DISABLE_HEALTH_CHECK_LOG:-false}
      # Opcional: desabilitar módulos para reduzir memória
      # - GOTENBERG_CHROMIUM_DISABLE=true
      # - GOTENBERG_LIBREOFFICE_DISABLE=true

    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    security_opt:
      - no-new-privileges:true

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.role == manager
      resources:
        limits:
          cpus: "2"
          memory: 2048M
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
      labels:
        - traefik.enable=true
        - traefik.http.routers.gotenberg.rule=Host(`${GOTENBERG_DOMAIN}`)
        - traefik.http.routers.gotenberg.entrypoints=websecure
        - traefik.http.routers.gotenberg.priority=1
        - traefik.http.routers.gotenberg.tls.certresolver=letsencryptresolver
        - traefik.http.routers.gotenberg.service=gotenberg
        - traefik.http.services.gotenberg.loadbalancer.server.port=3000
        - traefik.http.services.gotenberg.loadbalancer.passHostHeader=1
        - traefik.http.routers.gotenberg.middlewares=crowdsec-bouncer@swarm,security-headers@file,rate-limit@file

networks:
  swarm_public:
    external: true
    name: swarm_public
