# Postgres dedicado ao n8n (editor, worker, webhook).
# PgBouncer faz pool de conexões na frente do Postgres.
# Nos stacks do n8n use: DB_POSTGRESDB_HOST=n8n_pgbouncer e DB_POSTGRESDB_PORT=5432

services:

  n8n_postgres:
    image: pgvector/pgvector:pg17
    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data
    networks:
      - swarm_public
    environment:
      - POSTGRES_USER=${N8N_POSTGRES_USER:-n8n}
      - POSTGRES_PASSWORD=${N8N_POSTGRES_PASSWORD}
      - POSTGRES_DB=${N8N_POSTGRES_DB:-n8n}
      - TZ=${TIMEZONE:-America/Sao_Paulo}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n -d n8n"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    security_opt:
      - no-new-privileges:true

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.role == worker
          - node.labels.app == n8n
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5

  n8n_pgbouncer:
    image: edoburu/pgbouncer:latest
    networks:
      - swarm_public
    environment:
      # Conexão ao Postgres (backend). Host = nome do serviço na rede.
      DATABASE_URL: postgres://${N8N_POSTGRES_USER:-n8n}:${N8N_POSTGRES_PASSWORD}@n8n_postgres:5432/${N8N_POSTGRES_DB:-n8n}
      LISTEN_ADDR: "0.0.0.0"
      LISTEN_PORT: "5432"
      # Ignora parâmetros que o n8n envia na conexão (ex.: statement_timeout=300000).
      IGNORE_STARTUP_PARAMETERS: "extra_float_digits"
      # Session pooling: mantém a sessão por cliente (compatível com prepared statements do TypeORM/n8n).
      POOL_MODE: session
      SERVER_RESET_QUERY: "DISCARD ALL"
      MAX_CLIENT_CONN: "200"
      DEFAULT_POOL_SIZE: "20"
      AUTH_TYPE: scram-sha-256
      # Timeouts alinhados ao uso por editor/worker/webhook.
      SERVER_IDLE_TIMEOUT: "600"
      CLIENT_IDLE_TIMEOUT: "0"
      QUERY_TIMEOUT: "0"
      TZ: ${TIMEZONE:-America/Sao_Paulo}
      # Para o healthcheck conectar com o usuário do pool (evita "no such user: postgres").
      PGPASSWORD: ${N8N_POSTGRES_PASSWORD}
      N8N_POSTGRES_USER: ${N8N_POSTGRES_USER:-n8n}
      N8N_POSTGRES_DB: ${N8N_POSTGRES_DB:-n8n}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -p 5432 -U n8n -d n8n || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.role == worker
          - node.labels.app == n8n
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5

volumes:
  n8n_postgres_data:
    external: true
    name: n8n_postgres_data

networks:
  swarm_public:
    external: true
