# Redis dedicado ao n8n (fila Bull para editor, worker, webhook).
# Nos stacks do n8n use: QUEUE_BULL_REDIS_HOST=n8n_redis

services:

  n8n_redis:
    image: redis:latest
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --requirepass
      - ${N8N_REDIS_PASSWORD}
      - --port
      - "6379"

    volumes:
      - n8n_redis_data:/data

    networks:
      - swarm_public

    environment:
      - REDIS_PASSWORD=${N8N_REDIS_PASSWORD}

    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$$REDIS_PASSWORD\" ping | grep -q PONG"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

    read_only: true

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    security_opt:
      - no-new-privileges:true

    deploy:
      placement:
        constraints:
          - node.labels.role == worker
          - node.labels.app == n8n
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5

volumes:
  n8n_redis_data:
    external: true
    name: n8n_redis_data

networks:
  swarm_public:
    external: true
