version: "3.7"
services:

  ## --------------------------- ORION --------------------------- ##

  postgres:
    image: pgvector/pgvector:pg17 ## Versão do postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portainer_CyberView ## Nome da rede interna
    environment:
      ## Senha do postgres 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TIMEZONE}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_USER}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - portainer_CyberView
    depends_on:
      - postgres
      
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pgadmin.rule=Host(`${PGADMIN_DOMAIN}`)"
        - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
        - "traefik.http.routers.pgadmin.entrypoints=websecure"
        - "traefik.http.routers.pgadmin.tls=true"
        - "traefik.http.routers.pgadmin.tls.certresolver=letsencryptresolver"

volumes:
  postgres_data:
    external: true
    name: postgres_data
  pgadmin_data:
    external: true
    name: pgadmin_data

networks:
  portainer_CyberView:
    external: true
    name: portainer_CyberView
