version: "3.7"
services:

  redis:
    image: redis:latest
    command:
      - redis-server
      - --appendonly
      - yes
      - --requirepass ${REDIS_PASSWORD}
      - --port
      - "6379"

    volumes:
      - redis_data:/data

    networks:
      - main 

    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M
          
  
volumes:
  redis_data:
    external: true
    name: redis_data

networks:
  main:
    name: main
