services:

  redis:
    image: redis:7.4.7-alpine
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --requirepass
      - ${REDIS_PASSWORD}
      - --port
      - "6379"
      - --maxmemory
      - "384mb"
      - --maxmemory-policy
      - "allkeys-lru"

    volumes:
      - redis_data:/data

    networks:
      - swarm_public

    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$$REDIS_PASSWORD\" ping | grep -q PONG"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

    read_only: true

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    security_opt:
      - no-new-privileges:true

    deploy:
      placement:
        constraints:
          - node.labels.role == worker
      resources:
        limits:
          cpus: "1"
          memory: 512M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5

volumes:
  redis_data:
    external: true
    name: redis_data

networks:
  swarm_public:
    external: true
